name: Next Deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    container: quay.io/syfxlin/devspace
    defaults:
      run:
        working-directory: /app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes & Docker
        run: |-
          mkdir -p ~/.kube
          mkdir -p ~/.docker
          echo $KUBE_CONFIG > ~/.kube/config
          echo $DOCKER_CONFIG > ~/.docker/config.json
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DOCKER_CONFIG: ${{ secrets.DOCKER_CONFIG }}
      - name: Deploy to Kubernetes
        run: |-
          devspace deploy
