name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: quay.io/syfxlin/depker
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to docker
        run: |
          mkdir -p ~/.docker
          echo "$CA_PEM" > ~/.docker/ca.pem
          echo "$CERT_PEM" > ~/.docker/cert.pem
          echo "$KEY_PEM" > ~/.docker/key.pem
          depker do deploy -f .depker/depker.ts
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_TLS_VERIFY: 1
          CA_PEM: ${{ secrets.CA_PEM }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
