name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: quay.io/syfxlin/depker
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to docker
        run: |
          mkdir -p /home/runner/certs
          echo "$CA_PEM" > /home/runner/certs/ca.pem
          echo "$CERT_PEM" > /home/runner/certs/cert.pem
          echo "$KEY_PEM" > /home/runner/certs/key.pem
          depker do deploy -f .depker/depker.ts
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_CERT_PATH: /home/runner/certs
          DOCKER_TLS_VERIFY: 1
          CA_PEM: ${{ secrets.CA_PEM }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
